framework:
    notifier:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            medium: ['browser']
            low: ['browser']
        message_bus: false
        admin_recipients:
            - { email: admin@example.com }
